name: SourcePawn Compile
description: Setup and compile SourcePawn plugins, recursively finds all include paths
inputs:
    source-files:
        description: List of paths to compile sp extension only
        required: true
    exclude-paths:
        description: List of paths to exclude from the finding algorithm
        required: false
    output-path:
        description: Path to write the output files to - Names will be the same as the input file except the extension changed to smx - If not defined will put the smx file right next to the sp file
        required: false

runs:
    using: composite
    steps:
        - name: Setup SourcePawn
          uses: BeepIsla/setup-sp@master
          with:
              version: 1.12.x

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
              node-version: 19.x

        - name: Build
          shell: bash
          run: |
              ORIGINAL_CWD=$(pwd)
              cd ${{ github.action_path }}
              echo -e "${{ inputs.source-files }}" >> SOURCE_FILES.txt
              echo -e "${{ inputs.exclude-paths }}" >> EXCLUDE_PATHS.txt
              echo -e "${{ inputs.output-path }}" >> OUTPUT_PATH.txt
              npm ci
              node index.js $ORIGINAL_CWD
              cd $ORIGINAL_CWD
