name: SourcePawn Compile
description: Setup and compile SourcePawn plugins in a uniform way
inputs:
    source-files:
        description: List of paths to compile sp extension only
        required: true
    extra-include-paths:
        description: Additional include paths not parsed from "install.json"
        required: false
    install-json-path-override:
        description: Default path is "<working directory>/install.json"
        requireD: false
    output-path:
        description: Folder path to write the output files to, files will be "<input source>.smx"
        required: false
    github-access-token:
        description: Access token for downloading dependencies
        required: false

runs:
    using: composite
    steps:
        - name: Setup SourcePawn
          uses: rumblefrog/setup-sp@master
          with:
              version: 1.12.x

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
              node-version: 19.x

        - name: Build
          shell: bash
          run: |
              ORIGINAL_CWD=$(pwd)
              cd ${{ github.action_path }}
              echo -e "${{ inputs.source-files }}" >> SOURCE_FILES.txt
              echo -e "${{ inputs.extra-include-paths }}" >> EXTRA_INCLUDE_PATHS.txt
              echo -e "${{ inputs.output-path }}" >> OUTPUT_PATH.txt
              echo -e "${{ inputs.install-json-path-override }}" >> INSTALL_JSON_PATH_OVERRIDE.txt
              npm ci
              GITHUB_ACCESS_TOKEN="${{ inputs.github-access-token }}"
              node index.js $ORIGINAL_CWD
              cd $ORIGINAL_CWD
