name: test

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Run
              uses: ./
              with:
                  source-files: |
                      test/test.sp

            - name: Check output
              run: |
                  ls test
