name: test

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Run
              uses: ./
              with:
                  source-files: |
                      test/test.sp
                  extra-include-paths: |
                      test/include
                  install-json-path-override: test/install.json

            - name: Check output
              run: |
                  if [ -f "./test/test.smx" ]; then
                      ls test
                  else
                      echo "Could not find ./test/test.smx"
                      exit 1
                  fi
